### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ClearlyElevated** [Ianardo-DiCaprio/IanardoCogs#3]
```Done selecting cli flags
Starting Janitor-Bot...
Connected to Discord. Getting ready...
Loading packages...
[2019-07-23 00:26:04] [ERROR] red.downloader: Invalid JSON information file at path: C:\Users\VancP\Desktop\Janitor\cogs\RepoManager\repos\IanardoCogs\imdb\info.json
Traceback (most recent call last):
  File "C:\Users\VancP\AppData\Roaming\Python\Python37\site-packages\redbot\cogs\downloader\installable.py", line 151, in _process_info_file
    info = json.load(f)
  File "c:\users\vancp\appdata\local\programs\python\python37-32\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\users\vancp\appdata\local\programs\python\python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\vancp\appdata\local\programs\python\python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\vancp\appdata\local\programs\python\python37-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 5 (char 119)
[2019-07-23 00:26:04] [ERROR] red.downloader: Invalid JSON information file at path: C:\Users\VancP\Desktop\Janitor\cogs\RepoManager\repos\IanardoCogs\imdb\info.json
Traceback (most recent call last):
  File "C:\Users\VancP\AppData\Roaming\Python\Python37\site-packages\redbot\cogs\downloader\installable.py", line 151, in _process_info_file
    info = json.load(f)
  File "c:\users\vancp\appdata\local\programs\python\python37-32\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\users\vancp\appdata\local\programs\python\python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\vancp\appdata\local\programs\python\python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\vancp\appdata\local\programs\python\python37-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 5 (char 119)
```

**Comment by ClearlyElevated** [comment]
What does this mean?

**Comment by Ianardo-DiCaprio** [comment]
Should hopefully be fixed if you update.
