### ISSUE TITLE
Setup cogs 

### ISSUE THREAD

**Issue by Ronish1122** [Ianardo-DiCaprio/IanardoCogs#5]
Which cogs dose one need for basicsetup cog to function properly without any errors ?

**Comment by Ianardo-DiCaprio** [comment]
It's to easily set up these cogs, but I haven't updated my bot in a while so not sure if it still works with the latest version of Red, could you send me the error you are getting please?
AntiMentionSpam
BanCheck
Bank
Grenzpolizei
Casino
CleverBot
Dungeon
Economy
Filter
InfoChannel
Leaver
Lyrics
Mod
ModLog
Reports
Starboard
Tickets
Core
ReactRoles

**Comment by Ronish1122** [comment]
Yes here is the error 

```py
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/elixir/cogs/CogManager/cogs/basicsetup/basicsetup.py", line 28, in setup
    await self.basic_setup(ctx)
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/elixir/cogs/CogManager/cogs/basicsetup/basicsetup.py", line 308, in basic_setup
    await ctx.invoke(
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/context.py", line 129, in invoke
    if command.cog is not None:
AttributeError: 'NoneType' object has no attribute 'cog'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'cog'

```
Was wondering if you can do like the owner can set which cogs are to be used in the setup process

**Comment by Ianardo-DiCaprio** [comment]
When, through the setup does it do the error, or is it instantly?

**Comment by Ianardo-DiCaprio** [comment]
And wouldn't be possible as I have to manually type the questions, it only asks questions about cogs you have installed though, and you can just say no, to each thing.

**Comment by Ronish1122** [comment]
Yes the error occurs when setting up and I have a public bot so I can't really tell everyone not to use it

**Comment by Ianardo-DiCaprio** [comment]
All standard (none 3rd party cogs) that is has should now all work if you update.

**Comment by Ronish1122** [comment]
Yeah I tried but when I reply it still moves to the next question even if my answer is yes

**Comment by Ianardo-DiCaprio** [comment]
Which question? It's working for me.

**Comment by Ronish1122** [comment]
All questions I'll attach a ss ![Uploading 107626197...]

**Comment by Ronish1122** [comment]
![image](https://user-images.githubusercontent.com/55736291/107626215-78e94080-6c83-11eb-8995-444841ff41d0.png)

**Comment by Ianardo-DiCaprio** [comment]
If you answer yes, it should then ask questions to do with that cog, it's working for me.

**Comment by Ronish1122** [comment]
It isn't for me :/

**Comment by Ianardo-DiCaprio** [comment]
Iridium#6200
Could you DM me your bot's invite code please.

**Comment by Ronish1122** [comment]
Sure invite - https://top.gg/bot/732916004656513077/invite 
I'll send you a req
